FROM ubuntu:14.04
MAINTAINER Mads Hartmann <mads379@gmail.com>

RUN apt-get update
RUN apt-get install --yes git
RUN apt-get install --yes erlang
RUN apt-get install --yes make
RUN apt-get update
RUN apt-get install --yes python-dev
RUN apt-get install --yes python-pip
